// Auto-generated from responses-blind.json — do not edit manually
export interface EvalResponse {
    responseId: number;
    promptId: string;
    promptType: 'simple' | 'complex';
    prompt: string;
    blindLabel: string;
    approxTokens: number;
    response: string;
}

export const EVAL_RESPONSES: EvalResponse[] = [
    {
        responseId: 1,
        promptId: 'S01',
        promptType: 'simple',
        prompt: "What does the oil pressure warning light mean?",
        blindLabel: "Model B",
        approxTokens: 154,
        response: "The oil pressure warning light typically indicates low or insufficient oil pressure, which can lead to engine damage if not addressed immediately. Common causes include low oil levels, a faulty oil pump, clogged oil filter, or a malfunctioning oil pressure sensor. Check your oil level using the dipstick and top up if necessary. If the light remains on after adding oil, or if the engine makes knocking noises, **pull over safely and turn off the engine** – low oil pressure while running can cause catastrophic engine failure. Share your vehicle's make, model, year, and current mileage for more tailored advice.",
    },
    {
        responseId: 2,
        promptId: 'S01',
        promptType: 'simple',
        prompt: "What does the oil pressure warning light mean?",
        blindLabel: "Model A",
        approxTokens: 50,
        response: "The oil pressure warning light typically indicates a problem with the engine's oil pressure. This can be caused by low oil levels, a faulty oil pressure sensor, or a malfunctioning engine component.",
    },
    {
        responseId: 3,
        promptId: 'S02',
        promptType: 'simple',
        prompt: "How often should I change my air filter?",
        blindLabel: "Model B",
        approxTokens: 80,
        response: "Most vehicle manufacturers recommend replacing your air filter every 15,000 to 30,000 miles, but this can vary depending on driving conditions. If you frequently drive in dusty or dirty environments, consider checking or replacing it more often. Always consult your owner's manual for the exact interval for your vehicle.",
    },
    {
        responseId: 4,
        promptId: 'S02',
        promptType: 'simple',
        prompt: "How often should I change my air filter?",
        blindLabel: "Model A",
        approxTokens: 31,
        response: "You should check and replace your air filter every 15,000 to 30,000 miles, or as recommended by your vehicle's manufacturer.",
    },
    {
        responseId: 5,
        promptId: 'S03',
        promptType: 'simple',
        prompt: "What is wheel alignment and why does it matter?",
        blindLabel: "Model A",
        approxTokens: 104,
        response: "Wheel alignment refers to adjusting your vehicle's suspension system to ensure wheels are at the correct angles (camber, caster, toe). Proper alignment is critical because it affects tire wear, handling, fuel efficiency, and safety. Misaligned wheels can cause uneven tire wear, pulling to one side, and reduced stability. Get your alignment checked if you notice pulling, crooked steering wheel, or uneven tire wear.",
    },
    {
        responseId: 6,
        promptId: 'S03',
        promptType: 'simple',
        prompt: "What is wheel alignment and why does it matter?",
        blindLabel: "Model B",
        approxTokens: 60,
        response: "Wheel alignment, also known as tire alignment, is the process of adjusting the angles of your vehicle's wheels so they're properly lined up with each other. This ensures your tires wear evenly, improves handling, and enhances overall safety.",
    },
    {
        responseId: 7,
        promptId: 'S04',
        promptType: 'simple',
        prompt: "My battery warning light just came on while driving. What should I do?",
        blindLabel: "Model A",
        approxTokens: 83,
        response: "The battery warning light indicates a potential issue with your car's charging system or battery. Drive safely to a secure location and avoid sudden stops. Check for loose/corroded battery terminals if you're experienced, but this requires immediate professional diagnosis. I recommend booking an appointment for a full system check.",
    },
    {
        responseId: 8,
        promptId: 'S04',
        promptType: 'simple',
        prompt: "My battery warning light just came on while driving. What should I do?",
        blindLabel: "Model B",
        approxTokens: 96,
        response: "The battery warning light indicates a potential issue with the electrical system in your vehicle. I recommend checking the battery terminals for corrosion or loose connections, and charging the battery if the voltage is low. Additionally, if the light remains illuminated after checking, it's advised to take your vehicle to a professional mechanic for further diagnosis and repair.",
    },
    {
        responseId: 9,
        promptId: 'S05',
        promptType: 'simple',
        prompt: "What does it mean when my car pulls to one side while driving?",
        blindLabel: "Model A",
        approxTokens: 96,
        response: "A car that pulls to one side while driving is often caused by wheel misalignment, uneven tire pressure, or brake issues. First, check all tires for proper inflation and signs of uneven wear. If the pull is constant, misalignment is likely. If it happens only when braking, a stuck brake caliper or pad may be the cause. For a thorough diagnosis, I recommend visiting a professional.",
    },
    {
        responseId: 10,
        promptId: 'S05',
        promptType: 'simple',
        prompt: "What does it mean when my car pulls to one side while driving?",
        blindLabel: "Model B",
        approxTokens: 67,
        response: "Pulling to one side while driving can be a concerning issue. I'd like to help you identify the possible cause. Could you please tell me what type of vehicle you have (make, model, and year), and have you noticed any other symptoms, such as unusual noises or vibrations?",
    },
    {
        responseId: 11,
        promptId: 'S06',
        promptType: 'simple',
        prompt: "How do I know when my brake pads need replacing?",
        blindLabel: "Model B",
        approxTokens: 129,
        response: " Brake pads typically need replacement if you notice: 1) a high-pitched squealing/scratching noise when braking, 2) a grinding or rubbing sound, 3) vibration/pulsation in the brake pedal, 4) the car pulling to one side when braking, or 5) the brake warning light is on. Most brake pads last 30,000-70,000 miles depending on driving conditions. If you hear grinding noises or notice vehicle pulling, get inspected immediately. Can you share your vehicle's make, model, and year so I can give more specific guidance?",
    },
    {
        responseId: 12,
        promptId: 'S06',
        promptType: 'simple',
        prompt: "How do I know when my brake pads need replacing?",
        blindLabel: "Model A",
        approxTokens: 69,
        response: "To determine when your brake pads need replacing, look out for these signs: spongy brake pedal, unusual noise (grinding or squealing) when applying the brakes, or a vibration when driving. You can also check your owner's manual or look for a warning light on your dashboard.",
    },
    {
        responseId: 13,
        promptId: 'S07',
        promptType: 'simple',
        prompt: "What is engine coolant and how often should I top it up?",
        blindLabel: "Model A",
        approxTokens: 0,
        response: "",
    },
    {
        responseId: 14,
        promptId: 'S07',
        promptType: 'simple',
        prompt: "What is engine coolant and how often should I top it up?",
        blindLabel: "Model B",
        approxTokens: 52,
        response: "Engine coolant, also known as antifreeze, is a liquid solution that helps regulate engine temperature and prevent corrosion. It typically contains a 50/50 mix of water and ethylene glycol or propylene glycol.",
    },
    {
        responseId: 15,
        promptId: 'S08',
        promptType: 'simple',
        prompt: "My windshield washer fluid warning light is on. Is that serious?",
        blindLabel: "Model A",
        approxTokens: 107,
        response: "The windshield washer fluid warning light indicates the fluid level is low, which is a minor issue but important for visibility in inclement weather. Check the washer fluid reservoir under the hood—if it's empty, top it off with washer fluid. If the level was fine and the light stays on, there could be a clogged nozzle or faulty sensor. Is your windshield washer spraying properly now? What make/model/year vehicle do you have?",
    },
    {
        responseId: 16,
        promptId: 'S08',
        promptType: 'simple',
        prompt: "My windshield washer fluid warning light is on. Is that serious?",
        blindLabel: "Model B",
        approxTokens: 95,
        response: "The windshield washer fluid warning light can be an indication of a low washer fluid level, a faulty washer fluid sensor, or a clogged washer system. However, it's not usually a serious issue. Nevertheless, I would recommend checking your washer fluid reservoir to ensure it's filled. If the light remains on after checking the reservoir, it may indicate a more complex problem.",
    },
    {
        responseId: 17,
        promptId: 'S09',
        promptType: 'simple',
        prompt: "What causes a car to vibrate at highway speeds?",
        blindLabel: "Model B",
        approxTokens: 99,
        response: "Car vibrations at highway speeds can be caused by unbalanced tires, misaligned wheels, worn suspension components (like bushings or ball joints), driveshaft/CV joint issues, or warped brake rotors if braking causes the vibration. Could this be happening continuously or only when braking? Does the steering wheel vibrate too? Checking tire wear patterns and suspension components is recommended.",
    },
    {
        responseId: 18,
        promptId: 'S09',
        promptType: 'simple',
        prompt: "What causes a car to vibrate at highway speeds?",
        blindLabel: "Model A",
        approxTokens: 49,
        response: "Vibrations at highway speeds can be caused by several factors. Let's break them down and investigate further. Can you tell me more about your vehicle? What's the make, model, and year of your car?",
    },
    {
        responseId: 19,
        promptId: 'S10',
        promptType: 'simple',
        prompt: "How often should I rotate my tires?",
        blindLabel: "Model A",
        approxTokens: 86,
        response: "Tire rotation is typically recommended every 5,000 to 7,500 miles, but always check your vehicle's owner manual for the manufacturer's exact guidelines. Front-wheel-drive vehicles may need more frequent rotations due to uneven tire wear. If you notice uneven tire wear patterns, vibrations, or reduced handling, have your tires rotated sooner.",
    },
    {
        responseId: 20,
        promptId: 'S10',
        promptType: 'simple',
        prompt: "How often should I rotate my tires?",
        blindLabel: "Model B",
        approxTokens: 54,
        response: "Rotating your tires is a crucial maintenance task to ensure even tread wear and optimal performance. It's recommended to rotate your tires every 5,000 to 8,000 miles, or as specified in your vehicle's owner's manual.",
    },
    {
        responseId: 21,
        promptId: 'C01',
        promptType: 'complex',
        prompt: "My car loses power going uphill, I see blue smoke when I start it, and the engine sounds rough at idle. What could be wrong?",
        blindLabel: "Model A",
        approxTokens: 99,
        response: "Your symptoms point to a few potential issues. Blue smoke at startup typically indicates oil burning (worn piston rings or valve guides), while rough idle and power loss uphill could signal a misfire or oil in the combustion chamber. I’d recommend checking for a compression loss, spark plug condition, or oil consumption. To narrow it down, can you share your car’s make/model/year and mileage?",
    },
    {
        responseId: 22,
        promptId: 'C01',
        promptType: 'complex',
        prompt: "My car loses power going uphill, I see blue smoke when I start it, and the engine sounds rough at idle. What could be wrong?",
        blindLabel: "Model B",
        approxTokens: 44,
        response: "These symptoms can be indicative of engine issues, particularly with the piston rings, valves, or the engine's piston seal. I'd like to help you break down the possible causes.",
    },
    {
        responseId: 23,
        promptId: 'C02',
        promptType: 'complex',
        prompt: "My brakes feel soft and I hear grinding on the front left when I brake hard. Is it safe to drive?",
        blindLabel: "Model B",
        approxTokens: 79,
        response: "This is a critical safety issue. A soft brake pedal and grinding noises typically indicate severely worn brake pads (exposing metal) and damaged rotors. If the 'brake warning' light is on your dashboard or you smell burning, stop driving immediately. For safety, book a professional inspection as soon as possible.",
    },
    {
        responseId: 24,
        promptId: 'C02',
        promptType: 'complex',
        prompt: "My brakes feel soft and I hear grinding on the front left when I brake hard. Is it safe to drive?",
        blindLabel: "Model A",
        approxTokens: 45,
        response: "Considering your symptoms, I would advise against driving your vehicle until it's properly diagnosed and repaired to avoid potentially more serious problems such as a brake failure.",
    },
    {
        responseId: 25,
        promptId: 'C03',
        promptType: 'complex',
        prompt: "After a short drive my car starts smelling like burning rubber, the temperature gauge goes into the red, and the AC stopped working. What is happening?",
        blindLabel: "Model A",
        approxTokens: 0,
        response: "",
    },
    {
        responseId: 26,
        promptId: 'C03',
        promptType: 'complex',
        prompt: "After a short drive my car starts smelling like burning rubber, the temperature gauge goes into the red, and the AC stopped working. What is happening?",
        blindLabel: "Model B",
        approxTokens: 92,
        response: "Based on your symptoms, there are a few possible causes. A burning rubber smell, high temperature, and malfunctioning AC could be related. Here are some potential reasons: overheating engine, blown fuse, electrical issue, or a problem with the AC compressor or condenser. I'd recommend checking the coolant level and inspecting the radiator for any leaks or blockages.",
    },
    {
        responseId: 27,
        promptId: 'C04',
        promptType: 'complex',
        prompt: "My 2015 diesel SUV is hard to start in the morning, emits black smoke on acceleration, and fuel consumption has increased noticeably over the past month.",
        blindLabel: "Model A",
        approxTokens: 110,
        response: "Your 2015 diesel SUV's hard starting, black smoke, and increased fuel consumption could be caused by inefficient fuel combustion. Common causes include faulty fuel injectors (leaking or clogged), worn glow plugs, or air intake system issues. A more serious possibility is a clogged diesel particulate filter (DPF). I recommend checking glow plug function and inspecting injectors for issues. Would you like me to suggest a part or service?",
    },
    {
        responseId: 28,
        promptId: 'C04',
        promptType: 'complex',
        prompt: "My 2015 diesel SUV is hard to start in the morning, emits black smoke on acceleration, and fuel consumption has increased noticeably over the past month.",
        blindLabel: "Model B",
        approxTokens: 49,
        response: "Based on your description, it sounds like your 2015 diesel SUV might be experiencing issues related to its fuel system or engine management. I'd like to help you narrow down the possible causes.",
    },
    {
        responseId: 29,
        promptId: 'C05',
        promptType: 'complex',
        prompt: "I hear a loud clunking from the front when going over bumps, the steering feels loose, and there is uneven tire wear on the front left. Could these be related?",
        blindLabel: "Model B",
        approxTokens: 96,
        response: "These symptoms are likely related to worn suspension components. The clunking over bumps and loose steering suggest issues like worn control arm bushings, ball joints, or tie rod ends. The uneven tire wear may result from alignment issues caused by damaged suspension parts. I recommend checking these components urgently — if confirmed, replacement and alignment will be necessary.",
    },
    {
        responseId: 30,
        promptId: 'C05',
        promptType: 'complex',
        prompt: "I hear a loud clunking from the front when going over bumps, the steering feels loose, and there is uneven tire wear on the front left. Could these be related?",
        blindLabel: "Model A",
        approxTokens: 46,
        response: "These symptoms could be related to a front-end alignment, ball joint, or control arm issue. I recommend checking the vehicle's make, model, and year to determine the most likely cause.",
    },
    {
        responseId: 31,
        promptId: 'C06',
        promptType: 'complex',
        prompt: "My automatic gearbox sometimes refuses to shift from 2nd to 3rd, slips under hard acceleration, and the transmission fluid smells burnt. How urgent is this?",
        blindLabel: "Model B",
        approxTokens: 0,
        response: "",
    },
    {
        responseId: 32,
        promptId: 'C06',
        promptType: 'complex',
        prompt: "My automatic gearbox sometimes refuses to shift from 2nd to 3rd, slips under hard acceleration, and the transmission fluid smells burnt. How urgent is this?",
        blindLabel: "Model A",
        approxTokens: 42,
        response: "Based on your symptoms, I strongly recommend addressing this issue as soon as possible. Burnt transmission fluid can cause extensive damage to the transmission system.",
    },
    {
        responseId: 33,
        promptId: 'C07',
        promptType: 'complex',
        prompt: "The check engine light is on, the car judders when I accelerate, and I noticed the fuel cap was loose last week. Could a loose fuel cap really cause all these symptoms?",
        blindLabel: "Model B",
        approxTokens: 101,
        response: "The loose fuel cap could cause the check engine light due to evaporative system issues, but it's unlikely to cause juddering during acceleration. The juddering might indicate a separate issue like spark plug problems, misfires, or fuel system issues. I recommend tightening the fuel cap and clearing the code to see if the light stays off. If the juddering persists, a professional diagnostic is needed.",
    },
    {
        responseId: 34,
        promptId: 'C07',
        promptType: 'complex',
        prompt: "The check engine light is on, the car judders when I accelerate, and I noticed the fuel cap was loose last week. Could a loose fuel cap really cause all these symptoms?",
        blindLabel: "Model A",
        approxTokens: 34,
        response: "A loose fuel cap can cause some of the symptoms you're experiencing, but it's unlikely to cause all of them. Let's investigate further.",
    },
    {
        responseId: 35,
        promptId: 'C08',
        promptType: 'complex',
        prompt: "My car shakes violently only when braking from high speed, the brake pedal pulses under my foot, and stopping distance feels longer than usual.",
        blindLabel: "Model B",
        approxTokens: 105,
        response: "The symptoms you describe—violent shaking, pulsing brake pedal, and longer stopping distance—most commonly point to warped brake rotors. This causes uneven contact between brake pads and rotors, creating vibration and reduced stopping power. Less likely causes include glazed brake pads, uneven pad wear, or rotor surface damage. This issue requires immediate professional inspection to ensure safe braking performance.",
    },
    {
        responseId: 36,
        promptId: 'C08',
        promptType: 'complex',
        prompt: "My car shakes violently only when braking from high speed, the brake pedal pulses under my foot, and stopping distance feels longer than usual.",
        blindLabel: "Model A",
        approxTokens: 69,
        response: "I'm concerned there might be an issue with your brake system, particularly your brake pads or rotors. I recommend having them checked by a professional as soon as possible. In the meantime, please use caution and consider limiting your driving until the problem is resolved.",
    },
    {
        responseId: 37,
        promptId: 'C09',
        promptType: 'complex',
        prompt: "I hit a pothole two weeks ago and since then the car drifts right, there is a faint humming from the rear, and my tyres look fine visually. What could have been damaged?",
        blindLabel: "Model B",
        approxTokens: 0,
        response: "",
    },
    {
        responseId: 38,
        promptId: 'C09',
        promptType: 'complex',
        prompt: "I hit a pothole two weeks ago and since then the car drifts right, there is a faint humming from the rear, and my tyres look fine visually. What could have been damaged?",
        blindLabel: "Model A",
        approxTokens: 57,
        response: "It sounds like you may have damaged a suspension component after hitting the pothole. The drifting to the right and the humming noise from the rear could be related to a misalignment of the steering or a worn-out suspension part.",
    },
    {
        responseId: 39,
        promptId: 'C10',
        promptType: 'complex',
        prompt: "Steam is coming from under the hood, there is a sweet smell inside the cabin, the heater stopped producing warm air, and the engine temperature warning is flashing. What do I do right now?",
        blindLabel: "Model B",
        approxTokens: 123,
        response: "This is an urgent situation indicating an overheating engine and possible coolant leak. 1) Park safely and shut off the engine immediately. Do not touch anything hot. 2) Wait 30 minutes, then gently check coolant reservoir level - do NOT open the radiator cap when hot. 3) If coolant level is low, add 50/50 coolant mixture (if available). 4) Regardless of coolant level, get professional help immediately. The smell in the cabin and loss of heater warmth also suggest coolant vaporization.",
    },
    {
        responseId: 40,
        promptId: 'C10',
        promptType: 'complex',
        prompt: "Steam is coming from under the hood, there is a sweet smell inside the cabin, the heater stopped producing warm air, and the engine temperature warning is flashing. What do I do right now?",
        blindLabel: "Model A",
        approxTokens: 40,
        response: "Please pull over to a safe location as soon as possible. The engine temperature warning flashing and sweet smell inside the cabin could indicate a serious issue.",
    },
];

